In [43]:
print ("saira shairi.....")       
    

saira shairi.....


In [45]:

#Task 1.1:
nums = [3, 5, 7, 8, 12]


cubes = []


for num in nums:
    cubes.append(num ** 3)


print(cubes)

[27, 125, 343, 512, 1728]


In [27]:
#Task 1.2:
my_dict = {}


my_dict['parrot'] = 2
my_dict['goat'] = 4
my_dict['spider'] = 8
my_dict['crab'] = 10


print(my_dict)


{'parrot': 2, 'goat': 4, 'spider': 8, 'crab': 10}


In [29]:
#Task 1.3:
my_dict = {
    'parrot': 2,
    'goat': 4,
    'spider': 8,
    'crab': 10
}

# Initialization
total_legs = 0

# Looping
for animal, legs in my_dict.items():

    print(f'{animal}: {legs} legs')
    
    
    total_legs += legs

# Printing
print(f'Total number of legs: {total_legs}')


parrot: 2 legs
goat: 4 legs
spider: 8 legs
crab: 10 legs
Total number of legs: 24


In [41]:
#Task 1.4:
# Creating
A = (3, 9, 4, [5, 6])

# Modifying
A[3][0] = 8

# Printing
print(A)


(3, 9, 4, [8, 6])


In [47]:
# Task 1.5: Delete the tuple 
del A




In [39]:
#Task 1.6:
# Creation 
B = ('a', 'p', 'p', 'l', 'e')

# Counting number of 'p'
count_p = B.count('p')

# Printing
print(f"Number of occurrences of 'p': {count_p}")


Number of occurrences of 'p': 2


In [77]:
#Task 1.7:
# Creatin
B = ('a', 'p', 'p', 'l', 'e')

# Finding index 'l'
index_l = B.index('l')

# Printing
print(f"Index of 'l': {index_l}")



Index of 'l': 3


In [79]:
 # Task 2
import numpy as np

# 2.1 Convert matrix A into numpy array
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
print("Matrix A:\n", A)

Matrix A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [81]:
# 2.2 Use slicing 
b = A[:2, 1:3]  # First 2 rows, columns 1 and 2
print("Subarray b:\n", b)
print("Shape of b:", b.shape)

Subarray b:
 [[2 3]
 [6 7]]
Shape of b: (2, 2)


In [83]:
# 2.3 
C = np.empty_like(A)
print("Empty matrix C:\n", C)

Empty matrix C:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [85]:
# 2.4 
z = np.array([1, 0, 1])
for i in range(A.shape[1]):  # Iterate over columns
    C[:, i] = A[:, i] + z
print("Matrix C after adding z to each column:\n", C)

Matrix C after adding z to each column:
 [[ 2  3  4  5]
 [ 5  6  7  8]
 [10 11 12 13]]


In [87]:
# 2.5
X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
sum_XY = np.add(X, Y)
print("Sum of matrices X and Y:\n", sum_XY)

Sum of matrices X and Y:
 [[ 6  8]
 [10 12]]


In [89]:
# 2.6 
product_XY = np.multiply(X, Y)
print("Element-wise multiplication of matrices X and Y:\n", product_XY)

Element-wise multiplication of matrices X and Y:
 [[ 5 12]
 [21 32]]


In [91]:
# 2.7 
sqrt_Y = np.sqrt(Y)
print("Element-wise square root of matrix Y:\n", sqrt_Y)

Element-wise square root of matrix Y:
 [[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [93]:
# 2.8 
dot_Xv = np.dot(X, v)
print("Dot product of matrix X and vector v:\n", dot_Xv)

Dot product of matrix X and vector v:
 [29 67]


In [95]:
# 2.9 
sum_columns_X = np.sum(X, axis=0)
print("Sum of each column of matrix X:\n", sum_columns_X)

Sum of each column of matrix X:
 [4 6]


In [97]:
#Task 3:
#Task 3.1:
def Compute(distance, time):
    """Calculating velocity given distance and time."""
    if time == 0:
        raise ValueError("Time cannot be zero to avoid division by zero.")
    velocity = distance / time
    return velocity


distance = 100  
time = 20       
velocity = Compute(distance, time)
print(f"Velocity: {velocity} meters per second")



Velocity: 5.0 meters per second


In [99]:
#Task 3.2:
def mult(numbers):
    """Calculating product of all numbers in the list."""
    product = 1
    for num in numbers:
        product *= num
    return product

# Creation of list 
even_num = [2, 4, 6, 8, 10, 12]


product_of_evens = mult(even_num)
print(f"Product of even numbers: {product_of_evens}")


Product of even numbers: 46080


In [101]:
#Task 4:

import pandas as pd

# Create the DataFrame
data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

df = pd.DataFrame(data)
print("DataFrame:\n", df)


DataFrame:
    C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [103]:
#Task 4.1:
# Printing
print("\nFirst two rows of the DataFrame:\n", df.head(2))



First two rows of the DataFrame:
    C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5


In [105]:
#Task 4.2:
# Print 2nd 
print("\nSecond column:\n", df['C2'])



Second column:
 0    6
1    7
2    5
3    4
4    8
Name: C2, dtype: int64


In [107]:
#Task 4.3:
# Renaming
df.rename(columns={'C3': 'B3'}, inplace=True)
print("\nDataFrame after renaming column 'C3' to 'B3':\n", df)



DataFrame after renaming column 'C3' to 'B3':
    C1  C2  B3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [109]:
#Task 4.4:
df['Sum'] = 0
print("\nDataFrame after adding column 'Sum':\n", df)



DataFrame after adding column 'Sum':
    C1  C2  B3  C4  Sum
0   1   6   7   7    0
1   2   7   9   5    0
2   3   5   8   2    0
3   5   4   6   8    0
4   5   8   5   8    0


In [111]:
#Task 4.5:
df['Sum'] = df.sum(axis=1)
print("\nDataFrame with 'Sum' column updated:\n", df)



DataFrame with 'Sum' column updated:
    C1  C2  B3  C4  Sum
0   1   6   7   7   21
1   2   7   9   5   23
2   3   5   8   2   18
3   5   4   6   8   23
4   5   8   5   8   26


In [117]:
import pandas as pd
import os




In [119]:
pwd


'C:\\Users\\Shairi\\Desktop\\pyth1'

In [129]:
variable= pd.read_csv(r"C:\Users\Shairi\Desktop\pyth1\hello_sample.csv")
variable.head()


Gender F_Color   B_Month  Weight
0    Male   Black     March      77
1    Male     Red     March      72
2    Male   Black   October      53
3  Female    Blue  February      63
4    Male   black  October       80

In [133]:
#task 4.6
import pandas as pd

# Read the CSV file
df = pd.read_csv('hello_sample.csv')


In [135]:
#task 4.7
print(df)


    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  September       66


In [137]:
#task 4.8
print(df.tail(2))


   Gender F_Color     B_Month  Weight
21   Male  Yellow       April      74
22   Male     Red  September       66


In [139]:
#task 4.9
print(df.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Gender   23 non-null     object
 1   F_Color  23 non-null     object
 2   B_Month  23 non-null     object
 3   Weight   23 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 868.0+ bytes
None


In [141]:
#task 4.10
print(df.shape)


(23, 4)


In [143]:
#task 4.11
df_sorted = df.sort_values(by='Weight')
print(df_sorted)


    Gender  F_Color     B_Month  Weight
2     Male    Black     October      53
16    Male    Black      August      54
9     Male     Blue         May      58
7   Female      Red   September      59
18    Male  Mustard   December       60
10  Female      Red    October       60
6     Male   Orange      August      60
8     Male     Blue        July      60
3   Female     Blue    February      63
11    Male    Black   September      65
22    Male      Red  September       66
20    Male    Black   February       67
13    Male    Black       April      72
1     Male      Red       March      72
21    Male   Yellow       April      74
19  Female    Black    October       76
0     Male    Black       March      77
4     Male    black    October       80
17    Male    Black     January      82
12    Male    Green    December      85
14    Male    Green    January       90
15    Male   Yellow   November       90
5   Female    Black    december      97


In [145]:
#task 4.12
# this check missing values
print(df.isnull().sum())

# and now droping any rows with missing values
df_cleaned = df.dropna()
print(df_cleaned)


Gender     0
F_Color    0
B_Month    0
Weight     0
dtype: int64
    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male     